### ISSUE TITLE
Can't change SceneReference to None in inspector

### ISSUE THREAD

**Issue by harrisonmg** [NibbleByte/UnitySceneReference#1] opened 2021-12-08 03:37 UTC
Thanks for the great utility!

The old setting remains when I try to select None, and the following errors appear:

![image](https://user-images.githubusercontent.com/3968357/145144049-a1790794-2dc0-4d59-9bb0-202d6253a1d2.png)

**Comment by harrisonmg** [comment] 2021-12-09 04:43
Update: I managed to get rid of the errors based on this thread:

https://answers.unity.com/questions/533541/unsupported-type-error-in-custom-editor-script.html

But I still can't set to None...

**Comment by harrisonmg** [comment] 2021-12-09 05:30
Update: I have found that my problem is due to a limitation in the code:

`m_SceneAsset` is assumed uninitialized when it `== null`, so when set as such in the editor it just reloads the scene that `m_ScenePath` points to. I have made a modification to address this and will test it out for a while before submitting a PR.

**Comment by NibbleByte** [comment] 2021-12-12 09:08
That's a good find. You are right about the reason. The `m_SceneAsset` becomes null, which triggers `OnBeforeSerialize()` that tries to restore it from the `m_ScenePath`. I've committed a fix (70e684003e045fcb639adcaad9b22fb74458ab18) - if the property became null just now, clear the `m_ScenePath` as well. Test it out if it works and let me know to close the issue.

I'm not sure about the initial errors you were getting. I can't reproduce it. Can you give me more info on this? What Unity version are you using?

**Comment by harrisonmg** [comment] 2021-12-13 05:48
I think the errors are basically unrelated to this utility, and are detailed thoroughly in the post I linked above.

As far as I can tell the changes are working well! I think you can probably close the issue, thanks for your help!

**Closed as completed** 2021-12-14 18:28 UTC
